### ISSUE TITLE
Scrapy is not spidering the reports

### ISSUE THREAD

**Issue by briangnj** [timothyrenner/nuforc_sightings_data#18]
Scrapy closes the spider right after http://www.nuforc.org/webreports/ndxpost.html is crawled.  /data/raw/nuforc_reports_orig.json and data/raw/nuforc_reports_new.json are both empty and then the script exits

**Comment by timothyrenner** [comment]
Looks like they've renovated their site a little bit and the scraper needs to be updated. I'll try to take a look at this soon (super busy at the moment) but if I'm not fast enough feel free to open a PR.

**Comment by briangnj** [comment]
It looks like a new field was added (country) and they changed the report table formatting.  I fixed it, I'll open a PR when I get a free moment

**Comment by tsepton** [comment]
Hi @briangnj,

I do encounter the same issue (obviously), did you take the time to make that PR ?

**Comment by tsepton** [comment]
Nevermind, I had some spare time so I did it myself

**Comment by briangnj** [comment]
Sorry I didn't have a moment as I've been traveling. Thanks for updating
the code

**Comment by timothyrenner** [comment]
I've merged the PR, going to close. Thanks again @tsepton for the PR and thank you @briangnj for pointing this out!
